const USER_ROLES = {
  PATIENT: 'patient',
  DOCTOR: 'doctor',
  FINANCE_MANAGER: 'finance_manager',
  PHARMACIST: 'pharmacist',
  ADMIN: 'admin',
};

const ROLE_VALUES = Object.values(USER_ROLES);
const STAFF_ROLE_VALUES = [USER_ROLES.FINANCE_MANAGER, USER_ROLES.PHARMACIST];
const BILLING_MANAGER_ROLES = [USER_ROLES.FINANCE_MANAGER];
const DRUG_MANAGER_ROLES = [USER_ROLES.PHARMACIST];

module.exports = {
  USER_ROLES,
  ROLE_VALUES,
  STAFF_ROLE_VALUES,
  BILLING_MANAGER_ROLES,
  DRUG_MANAGER_ROLES,
};
